spring.application.name=SB-Ecommerce

# Search http://localhost:8080/h2-console on browser to open H2 Database
# jdbc is the connection protocol and h2 is the actual in memory database
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# By default --> Create and then destroy schema at the end of the session
spring.jpa.hibernate.ddl-auto=create-drop

